import os
import re
import json

from openai import OpenAI

# Load the client for OpenAI models
# Replace "os.environ['OPENAI_API_KEY']" with your OpenAI API key
client = OpenAI(
    api_key=os.environ['OPENAI_API_KEY'],
)

# global variables for the script
gpt4_prompts_path = "hintGen/prompts/gpt4_prompts.json"
all_prompts_path = "hintGen/prompts/all_prompts.json"
context_prompt_path = "hintGen/prompts/context_prompts.json"

def get_prompts(prompts_path):
    """
        A function to fetch the prompts from a .json file.
    """
    with open(prompts_path, 'r') as prompt_file:
        prompts = json.load(prompt_file)

    return prompts

def process_hints(hints_str):
    """ A function to process the hints generated by the model.
    Args:
        hints_str (str): hints generated by the model.
    Returns:
        hints (list of str): processed hints.
    """
    final_hints = []
    for hint in hints_str.split('\n'):
        hint = hint.strip()
        hint = re.sub(r'^[-+]?[0-9]+. ', '', hint)
        hint = re.sub(r'^[-+]?[0-9]+\) ', '', hint)
        hint = re.sub(r'^Hint [-+]?[0-9]+: ', '', hint)
        hint = re.sub(r'^Hint[-+]?[0-9]+: ', '', hint)
        hint = re.sub('Hint: ', '', hint)
        final_hints.append(hint)
    return final_hints


def generate_hints_from_gpt(prompts, _question, _answer, _context, _model='gpt-3.5-turbo', _with_context=False):
    """ A function that runs OpenAI's GPT models on the prompts to generate hints for the given question.
    Args:
        prompts ()                : a list of prompts for the model. Look at "prompts/all_prompts.json" for reference.
        _question (str)           : question for which the hint is to be generated.
        _answer (str)             : answer for the given question. Expects None if not available.
        _context (str)            : context for the given question. Expects None if not available.
        _model(str)               : a string that can take values 'gpt-4', 'gpt-3.5-turbo'
        _with_context             : a boolean to indicate if the context is to be used in the prompt.
    Returns:
        hints (list of str): hints generated for the given question.
    """

    generated_hints = []
    for prompt_category in prompts:
        for prompt in prompt_category['prompts']:
            curr_message = prompt['prompt']

            # replace the question and answer placeholders in the prompt
            curr_message = curr_message.replace('[question]', _question)
            if _answer is None:
                curr_message = curr_message.replace('[answer]', 'Not available.')
            else:
                curr_message = curr_message.replace('[answer]', _answer)
            if _with_context:
                if _context is None:
                    curr_message = curr_message.replace('[context]', 'Not available.')
                else:
                    curr_message = curr_message.replace('[context]', _context)
        
            counter = 0
            response = 'ERROR OCCURRED!'
            while counter < 20 and response == 'ERROR OCCURRED!':
                try:
                    counter += 1
                    chat = client.chat.completions.create(
                        model=_model,
                        messages=[{"role": "user", "content": curr_message}]
                    )
                    response = chat.choices[0].message.content
                except Exception as e:
                    response = 'ERROR OCCURRED!'
                    print('Error occured:', e)
            
            # process the generated hints to create a list of hints from a string of 10 hints
            hints = process_hints(response)
            # append the generated hints to the list
            generated_hints.extend(hints)
    
    return generated_hints

def generate_custom_hints(_question, _answer, _context):
    """ A function to generate custom hints for a given question.
    Args:
        _question (str)     : question for which hints are to be generated.
        _answer (str)       : answer for the given question. Expects None if not available.
        _context (str)      : context for the given question. Expects None if not available.
    Returns:
        hints (str): custom hints for the given question.
    """

    all_prompts     = get_prompts(all_prompts_path)
    gpt4_prompts    = get_prompts(gpt4_prompts_path)
    context_prompts = get_prompts(context_prompt_path)

    # A list of all hints generated by this function
    hints = []

    # generate hints using gpt3.5-turbo model with all prompts
    # gpt35_all_prompts_hints = generate_hints_from_gpt(all_prompts, _question, _answer, _context, 'gpt-3.5-turbo')
    # hints.extend(gpt35_all_prompts_hints)

    # generate hints using gpt4 model with gpt4 prompts
    gpt4_prompts_hints = generate_hints_from_gpt(gpt4_prompts, _question, _answer, _context, 'o4-mini')# 'gpt-3.5-turbo')# 'gpt-4')
    hints.extend(gpt4_prompts_hints)

    # generate hints using gpt3.5-turbo model with context prompts
    if _context is not None:
        gpt35_context_prompts_hints = generate_hints_from_gpt(context_prompts, _question, _answer, _context, 'o4-mini', _with_context=True)
        hints.extend(gpt35_context_prompts_hints)
    
    return hints