import os
import json
import tqdm
import requests

# change this to your own path and token
os.environ['HF_TOKEN'] = ""
os.environ['HF_HOME'] = ""

# global variables
OLLAMA_URL = "http://localhost:11434/api/generate" # Replace with your generation URL
hint_chain_size = 4
out_dir = "output/baseline_generations"

static_hint_prompt = f"""Generate {hint_chain_size} hints for this question-answer pair that will help a student answer the question. The hints should be concise and clear, and should guide the learner towards the correct answer without revealing it. Each hint should be a single sentence or phrase. Make sure that each next hint builds on the previous, gradually leading the learner to the answer. Generate the hints directly in bullet point format.

Question: {{question}}
Answer: {{answer}}
Hints:
"""

dynamic_hint_prompt = f"""Generate a single hint for this question-answer pair that will help a student answer the question. The hint should be concise and clear, guiding the learner towards the correct answer without revealing it. The hint should be a single sentence or phrase. You are provided with the interaction of the learner with the system so far, including their attempted answers and previous hints. Use the information from their interaction to provide a useful hint to help them answer the question. Generate the hint directly in a bullet point format.


Question: {{question}}
Answer: {{answer}}
{{conversation_str}}
Hint:
"""

def clean_hint(hint, hint_chain_size):
    # a function to clean the hint generated by the model (remove unwanted characters, etc.)
    # sometimes this isn't sufficient, and post-processing is required (see postprocess_hints.ipynb for that)

    # Remove any leading/trailing whitespace
    hint = hint.strip()

    # remove the thinking part if it exists
    if '</think>' in hint:
        hint = hint.split('</think>')[-1].strip()
    
    # Remove any unwanted characters or formatting
    hint = hint.replace('\n', ' ').replace('\r', '')
    
    # Remove the unwanted starters from the hint
    unwanted_starters = ['- ', ' -', '•', ' •', ':']
    for i in range(1, hint_chain_size+1):
        unwanted_starters.append(f'Hint {i} - ')
        unwanted_starters.append(f'- **Hint {i}**')
        unwanted_starters.append(f'**Hint {i}**')
        unwanted_starters.append(f'**Hint {i}:**')
        unwanted_starters.append(f'Hint {i}')
    
    unwanted_starters.append(':')
    unwanted_starters.append('-')
    
    for starter in unwanted_starters:
        if hint.startswith(starter):
            hint = hint[len(starter):].strip()

    # Remove any extra spaces
    hint = ' '.join(hint.split())

    return hint

def generate_static_hints(sciq_data, prompt_str, hint_chain_size, model_name="mistral-small:24b"):
    """
    Generate hints for all questions in the SCiQ validation set using the OLLAMA API.
    """
    all_hints = {}
    sciq_data = sciq_data[:5] # testing
    for inst_idx, inst in tqdm.tqdm(enumerate(sciq_data), total=len(sciq_data)):
        question = inst['question']
        answer = inst['correct_answer']
        
        # prepare the payload
        payload = {
            "model": model_name,
            "prompt": prompt_str.format(question=question, answer=answer),
            "think": False,
            "stream": False
        }
        
        # make the request to the OLLAMA API
        response = requests.post(OLLAMA_URL, json=payload)
        
        if response.status_code == 200:
            hints = response.json()['response'].strip().split('\n')
            hints = [clean_hint(hint, hint_chain_size) for hint in hints if hint.strip()]
            
            # save the hints back to the instance
            all_hints[question] = hints
        else:
            print(f"Error: {response.status_code} - {response.text} for question: {question}")

    # save the hints to a file
    json.dump(all_hints, open(f"{out_dir}/{model_name.replace(':', '-')}_valid.json", 'w'), indent=4)

    return all_hints

def generate_dynamic_hints(sciq_data, prompt_str, hint_chain_size, model_name="mistral-small:24b"):
    """
    Generate hints for all questions in the SCiQ validation set using the OLLAMA API.
    """
    sciq_data = sciq_data[:5]
    all_hints = {}
    for inst_idx, inst in tqdm.tqdm(enumerate(sciq_data), total=len(sciq_data)):
        question = inst['question']
        answer = inst['correct_answer']
        distractors = [inst['distractor1'], inst['distractor2'], inst['distractor3']]

        curr_hints = []
        # generate the first hint without any wrong answer attempts
        payload = {
            "model": model_name,
            "prompt": prompt_str.format(question=question, answer=answer, conversation_str=""),
            "think": False,
            "stream": False
        }

        # make the request to the OLLAMA API
        response = requests.post(OLLAMA_URL, json=payload)
        if response.status_code == 200:
            hint = response.json()['response'].strip()
            curr_hints.append(clean_hint(hint, hint_chain_size))
        else:
            print(f"Error: {response.status_code} - {response.text} for question: {question}")
            
        for distractor_idx, distractor in enumerate(distractors):
            hints_str = '\n'.join([f'Hint {i+1}: {curr_hints[i]}' for i in range(len(curr_hints))]) + "\n" + f"Hint {len(curr_hints) + 1}"
            # prepare the payload
            interaction_str = "Learner's Interaction:\n"
            for i in range(distractor_idx+1):
                interaction_str += f'Hint {i+1}: {curr_hints[i]}\n'
                interaction_str += f'Attempted Answer: {distractors[i]}\n'
                
            payload = {
                "model": model_name,
                "prompt": prompt_str.format(question=question, 
                                            answer=answer, 
                                            conversation_str=interaction_str),
                "stream": False
            }
            
            # make the request to the OLLAMA API
            response = requests.post(OLLAMA_URL, json=payload)
            
            if response.status_code == 200:
                hint = response.json()['response'].strip()
                curr_hints.append(clean_hint(hint, hint_chain_size))
            else:
                print(f"Error: {response.status_code} - {response.text} for question: {question}")
        
        all_hints[question] = curr_hints

    # save the hints to a file
    json.dump(all_hints, open(f"{out_dir}/{model_name.replace(':', '-')}_adaptive_valid.json", 'w'), indent=4)

    return all_hints

if __name__ == "__main__":
    # load the validation set from SCiQ
    sciq_val = json.load(open(f"../data/SciQ/valid.json", 'r'))

    model_names = ["gemma3:1b", "gemma3:4b", "gemma3:12b", "gemma3:27b",
                   "deepseek-r1:1.5b", "deepseek-r1:7b", "deepseek-r1:8b", "deepseek-r1:14b", "deepseek-r1:32b",
                   "qwen3:0.6b", "qwen3:1.7b", "qwen3:4b", "qwen3:8b", "qwen3:14b", "qwen3:30b", "qwen3:32b",
                   "phi4:14b", "mistral-small:24b"]

    for _model_name in model_names:
        print(f"Processing model: {_model_name}")
        
        if not os.path.exists(f"{out_dir}/{_model_name.replace(':', '-')}_static_valid.json"):
            print("Generating static hints...")
            generate_static_hints(sciq_val, static_hint_prompt, hint_chain_size, model_name=_model_name)
        else:
            print(f"Static hints already generated for {_model_name}, skipping...")
        if not os.path.exists(f"{out_dir}/{_model_name.replace(':', '-')}_dynamic_valid.json"):
            print("Generating dynamic hints...")
            generate_dynamic_hints(sciq_val, dynamic_hint_prompt, hint_chain_size, model_name=_model_name)
        else:
            print(f"Dynamic hints already generated for {_model_name}, skipping...")
